name: Build and test

on:
  push: # Run on pushes to the default branch
    branches: [main]
  pull_request: # Also run on pull requests originated from forks
    branches: [main]
  release:
    types: ["created"]

# This allows a subsequently queued workflow run to interrupt and cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Authorize:
    environment: ${{ github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: true

  Build-Docs:
    needs: Authorize
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
        with:
          version: "0.7.13"

      - name: Install packages and dependencies
        run: uv tool install hatch

      - name: Build Docs
        run: hatch run docs:build

  Deploy-Pages:
    needs: Authorize
    if: github.event_name == 'push' || github.event_name == 'release'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
        with:
          version: "0.7.13"

      - name: Install packages and dependencies
        run: uv tool install hatch

      - name: Deploy Docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin gh-pages --depth=1 || true

          if [[ $GITHUB_EVENT_NAME == "release" ]]; then
              hatch run docs:gh-release
          else
              hatch run docs:gh-deploy
          fi

  build-n-publish:
    needs: Authorize
    if: github.event_name == 'release'
    name: Build and publish Python üêç distributions üì¶ to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/airflow-provider-great-expectations/
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
          architecture: "x64"
      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
        with:
          version: "0.7.13"
      - name: Verify Git Tag and package version
        env:
          GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}
        run: python3 .github/scripts/verify_tag_and_version.py
      - run: uv build --wheel --sdist
      - run: uv publish
